/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AddEditCompany: typeof import('./src/pages/parentCompany/components/AddEditCompany/index.vue')['default']
    BalanceRemind: typeof import('./src/pages/parentCompany/components/CompanyInfo/BalanceRemind.vue')['default']
    Breadcrumbs: typeof import('./src/components/public/Breadcrumbs/index.vue')['default']
    CommonSetting: typeof import('./src/pages/parentCompany/components/RuleSetting/CommonSetting.vue')['default']
    CompanyDialog: typeof import('./src/pages/parentCompany/components/AddEditCompany/CompanyDialog.vue')['default']
    CompanyInfo: typeof import('./src/pages/parentCompany/components/CompanyInfo/index.vue')['default']
    CompanyList: typeof import('./src/pages/parentCompany/components/CompanyList/index.vue')['default']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RuleSetting: typeof import('./src/pages/parentCompany/components/RuleSetting/index.vue')['default']
  }
}
