/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AddEditCompany: typeof import('./src/pages/parentCompany/components/AddEditCompany/index.vue')['default']
    AddEditInvoiceTitle: typeof import('./src/pages/parentCompany/components/CompanyInfo/AddEditInvoiceTitle.vue')['default']
    BalanceRemind: typeof import('./src/pages/parentCompany/components/CompanyInfo/BalanceRemind.vue')['default']
    Breadcrumbs: typeof import('./src/components/public/Breadcrumbs/index.vue')['default']
    CommonSetting: typeof import('./src/pages/parentCompany/components/RuleSetting/CommonSetting.vue')['default']
    CompanyDialog: typeof import('./src/pages/parentCompany/components/AddEditCompany/CompanyDialog.vue')['default']
    CompanyInfo: typeof import('./src/pages/parentCompany/components/CompanyInfo/index.vue')['default']
    CompanyList: typeof import('./src/pages/parentCompany/components/CompanyList/index.vue')['default']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElOptionGroup: typeof import('element-plus/es')['ElOptionGroup']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    InvoiceAddress: typeof import('./src/pages/parentCompany/components/InvoiceAddress/index.vue')['default']
    InvoiceTable: typeof import('./src/pages/invoice/components/InvoiceTable.vue')['default']
    InvoiceTitle: typeof import('./src/pages/parentCompany/components/CompanyInfo/InvoiceTitle.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RuleSetting: typeof import('./src/pages/parentCompany/components/RuleSetting/index.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
